#!/bin/bash

# set -e # Errors are fatal
set -x # Show commands

date

# Update dependencies.
# yes | $FILES_ROOT/Tools/gtk/install-dependencies
# 
# # Install or update jhbuild.
# if [[ -d "$FILES_ROOT/WebKitBuild/DependenciesGTK" ]]; then
# 	$(JHBUILD_RUN_AS_ROOT=1 $FILES_ROOT/Tools/Scripts/update-webkitgtk-libs)
# else
# 	$(JHBUILD_RUN_AS_ROOT=1 $FILES_ROOT/Tools/jhbuild/jhbuild --gtk update)
# fi

# Add the special clang flags.
# eval "$($MOZSEARCH_PATH/scripts/indexer-setup.py)"

# export CC="clang -Xclang -load -Xclang /root/mozsearch/clang-plugin/libclang-index-plugin.so -Xclang -add-plugin -Xclang mozsearch-index -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/ -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/analysis -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/target/ -Xclang -fparse-all-comments"
# export CXX="clang++ -Xclang -load -Xclang /root/mozsearch/clang-plugin/libclang-index-plugin.so -Xclang -add-plugin -Xclang mozsearch-index -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/ -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/analysis -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/target/ -Xclang -fparse-all-comments"
# export RUSTFLAGS="-Zsave-analysis"

# cmake $FILES_ROOT -DPORT=JSC -DCMAKE_BUILD_TYPE=Debug
# cmake /root/webkit-index/webkit/WebKit/ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DPORT=JSCOnly
# cmake $FILES_ROOT -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_BUILD_TYPE=Debug -DPORT=JSCOnly

echo "### Build"

mkdir -p $OBJDIR
cd $OBJDIR

cmake $FILES_ROOT \
    -DCMAKE_C_COMPILER="clang" \
    -DCMAKE_CXX_COMPILER="clang++" \
    -DCMAKE_C_FLAGS="-Xclang -load -Xclang /root/mozsearch/clang-plugin/libclang-index-plugin.so -Xclang -add-plugin -Xclang mozsearch-index -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/ -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/analysis -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/target/ -Xclang -fparse-all-comments" \
    -DCMAKE_CXX_FLAGS="-Xclang -load -Xclang /root/mozsearch/clang-plugin/libclang-index-plugin.so -Xclang -add-plugin -Xclang mozsearch-index -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/ -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/analysis -Xclang -plugin-arg-mozsearch-index -Xclang /root/jsc-index/webkit/WebKit/target/ -Xclang -fparse-all-comments" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DPORT=JSCOnly

make -j$(nproc)
cd -

date
