#!/usr/bin/env bash

# set -e # Errors are fatal
# set -x # Show commands

date

# Clang is required.
CC=${CC:-clang-8}
CXX=${CXX:-clang++-8}

# Default WebKit port.
PORT=${PORT:-GTK}

# Obtain the special clang flags.
eval "$($MOZSEARCH_PATH/scripts/indexer-setup.py)"

# C Flags are encoded into CC var.
# Remove prefix (clang) and store flags into C_FLAGS.
C_FLAGS=${CC:6}

# CXX Flags are encoded into CXX var.
# Remove prefix (clang++) and store flags into CXX_FLAGS.
CXX_FLAGS=${CXX:8}

$FILES_ROOT/Tools/Scripts/update-webkitgtk-libs

mkdir -p $OBJDIR
cd $OBJDIR

cmake $FILES_ROOT \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DCMAKE_C_FLAGS="$C_FLAGS" \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DUSE_WPE_RENDERER=OFF \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DCMAKE_BUILD_TYPE=Debug \
    -DPORT=$PORT

make -j$(nproc)
cd -

date
